<?php

namespace api\modules\v1\controllers;

use Yii;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\Controller;

class StudentsController extends Controller {

    public function behaviors() {
        return [
            [
                'class' => 'yii\filters\ContentNegotiator',
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index' => ['GET'],
                ],
            ],
            'corsFilter' => [
                'class' => \yii\filters\Cors::className(),
                'cors' => [
                    'Origin' => ['*'],
                ],
            ],
        ];
    }

    public function actionIndex() {
        $students = [
            [
                'id' => 1,
                'name' => 'title1',
                'surname' => 'loc1',
                'age' => '1',
                'internship' => '0',
            ],
            [
                'id' => 2,
                'name' => 'anurag',
                'surname' => 'yadav',
                'age' => '20',
                'internship' => '1',
            ],
            [
                'id' => 3,
                'name' => 'celina',
                'surname' => 'gupta',
                'age' => '19',
                'internship' => '1',
            ],
            [
                'id' => 4,
                'name' => 'taran',
                'surname' => 'loc2',
                'age' => '16',
                'internship' => '1',
            ],
            [
                'id' => 81,
                'name' => 'title1',
                'surname' => 'loc1',
                'age' => '1',
                'internship' => '0',
            ],
            [
                'id' => 82,
                'name' => 'anurag',
                'surname' => 'yadav',
                'age' => '20',
                'internship' => '1',
            ],
            [
                'id' => 83,
                'name' => 'celina',
                'surname' => 'gupta',
                'age' => '19',
                'internship' => '1',
            ],
            [
                'id' => 84,
                'name' => 'taran',
                'surname' => 'loc2',
                'age' => '16',
                'internship' => '1',
            ],
            [
                'id' => 5,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 6,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 7,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 8,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 9,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 10,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 11,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 12,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 13,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 14,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 15,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 16,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 17,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 18,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 19,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 20,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 21,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 22,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 23,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 24,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 25,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 26,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 27,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 28,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 29,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 30,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 31,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 32,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 33,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 34,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 35,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 36,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 37,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 38,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 39,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 40,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 41,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 42,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 43,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 44,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 45,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 46,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 47,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 48,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 49,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 50,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 51,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 52,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 53,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 54,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 55,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 56,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 57,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 58,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 59,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 60,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 61,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 62,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 63,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 64,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 65,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 66,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 67,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 68,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 69,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 70,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 71,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 72,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 73,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 74,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 75,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 76,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 77,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 78,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 79,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
            [
                'id' => 80,
                'name' => 'sehdev',
                'surname' => 'Thapar',
                'age' => '25',
                'internship' => '1',
            ],
        ];
        return [
            'students' => $students,
        ];
    }

}
