<div class="col-md-9 col-sm-9 bal_builder">
    <div class="portlet light portlet-fit">
        <div class="portlet-body zero-padding">
            <div id="error_placement"></div>
            <div class="box_input">
                <div id="wait"><img src='http://bestanimations.com/Science/Gears/loadinggears/loading-gear-3-3.gif' width="100" height="100" /></div>
                <div class="default-text" id="dragdrop">Drag and Drop the form fields here to create your questionnaire.</div>
                <div class="form_builder_area">
                    <?php
                    if (!empty($fields)):
                    foreach ($fields['questionnaireFields'] as $field) {
                        switch ($field['field_type']) {
                            case 'text':
                                echo '<div class="li_56430 form_builder_field" style="width: 928.75px; height: 170px;"><div class="all_div"><div class="row li_row"><div class="col-md-6"><button type="button" class="btn btn-primary btn-sm remove_bal_field " data-field="56430"><i class="fa fa-times"></i></button></div><div class="col-md-6"><div class="form-check pull-right"><label class="form-check-label"><input data-field="56430" type="checkbox" class="form-check-input form_input_req" checked="">Required</label></div></div></div></div><hr><div class="row li_row form_output" data-type="text" data-field="56430"><div class="col-md-12"><div class="form-group"><input type="text" name="label_56430" class="form-control form_input_label valid_input" placeholder="Enter Short Question" data-field="56430" value="' . $field['field_label'] . '"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name="placeholder_56430" data-field="56430" class="form-control form_input_placeholder" placeholder="Placeholder"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name=' . $field['field_name'] . ' class="form-control form_input_name" placeholder="Name" value="text-field_56430"></div></div></div></div>';
                                break;
                            case 'textarea':
                                echo '<div class="li_75717 form_builder_field" style="width: 928.75px; height: 170px;"><div class="all_div"><div class="row li_row"><div class="col-md-6"><button type="button" class="btn btn-primary btn-sm remove_bal_field " data-field="75717"><i class="fa fa-times"></i></button></div><div class="col-md-6"><div class="form-check pull-right"><label class="form-check-label"><input data-field="75717" type="checkbox" class="form-check-input form_input_req" checked="">Required</label></div></div></div></div><hr><div class="row li_row form_output" data-type="textarea" data-field="75717"><div class="col-md-12"><div class="form-group"><input type="text" name="label_75717" class="form-control form_input_label valid_input" placeholder="Long Question" data-field="75717" value="' . $field['field_label'] . '"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name="placeholder_75717" data-field="75717" class="form-control form_input_placeholder" placeholder="Placeholder"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name=' . $field['field_name'] . ' class="form-control form_input_name" placeholder="Name" value="text-area_75717"></div></div></div></div>';
                                break;
                            case 'select':
                                foreach ($field['questionnaireFieldOptions'] as $options) {
                                    $select_inputs .= '<div data-field="90948" class="row select_row_90948" data-opt="50840"><div class="col-md-4"><div class="form-group"><input type="text" placeholder="Option" class="s_opt form-control valid_input" value = "' . $options['field_option'] . '"></div></div><div class="col-md-4"><i class="margin-top-5 fa fa-plus-circle fa-2x default_blue add_more_select" data-field="90948"></i></div><div class="col-md-4"><div class="form-group"><input type="hidden" value="Value" class="s_val form-control"></div></div></div>';
                                }
                                foreach ($field['questionnaireFieldOptions'] as $options) {
                                    $select .= '<option data-opt="50840" value="Value">' . $options['field_option'] . '</option>';
                                }
                                echo '<div class="li_90948 form_builder_field" style="width: 928.75px; height: 253px;"><div class="all_div"><div class="row li_row"><div class="col-md-12"><button type="button" class="btn btn-primary btn-sm remove_bal_field " data-field="90948"><i class="fa fa-times"></i></button></div></div><hr><div class="row li_row form_output" data-type="select" data-field="90948"><div class="col-md-12"><div class="form-group"><input type="text" name="label_90948" class="form-control form_input_label valid_input" placeholder="Dropdown Select Field" data-field="90948" value="' . $field['field_label'] . '"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name="text_90948" class="form-control form_input_name" placeholder="Name" value="name_90948"></div></div><div class="col-md-12"><div class="form-group"><select name="select_90948" class="form-control">' . $select . '</select></div></div></div><div class="row li_row"><div class="col-md-12"><div class="field_extra_info_90948">' . $select_inputs . '</div></div></div></div></div>';
                                break;
                            case 'radio':
                                foreach ($field['questionnaireFieldOptions'] as $options) {
                                    $radio .= '<label class="mt-radio mt-radio-outline"><input data-opt="44842" type="radio" name=' . $field['field_name'] . ' value="Value"><p class="r_opt_name_44842">' . $options['field_option'] . '</p><span></span></label>';
                                }
                                foreach ($field['questionnaireFieldOptions'] as $options) {
                                    $radio_inputs .= '<div data-field="90345" class="row radio_row_90345" data-opt="44842"><div class="col-md-4"><div class="form-group"><input type="text" placeholder="Option" class="r_opt form-control valid_input valid" aria-invalid="false" value=' . $options['field_option'] . '></div></div><div class="col-md-4"><i class="margin-top-5 fa fa-plus-circle fa-2x default_blue add_more_radio" data-field="90345"></i></div><div class="col-md-4"><div class="form-group"><input type="hidden" value="Value" class="r_val form-control"></div></div></div>';
                                }
                                echo '<div class="li_90345 form_builder_field" style="width: 928.75px; height: auto;"><div class="all_div"><div class="row li_row"><div class="col-md-12"><button type="button" class="btn btn-primary btn-sm remove_bal_field " data-field="90345"><i class="fa fa-times"></i></button></div></div><hr><div class="row li_row form_output" data-type="radio" data-field="90345"><div class="col-md-12"><div class="form-group"><input type="text" name="label_90345" class="form-control form_input_label valid_input valid" placeholder="Choice Fields" value=' . $field['field_label'] . ' data-field="90345" aria-invalid="false"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name="text_90345" class="form-control form_input_name" placeholder="Name" value=' . $field['field_name'] . '></div></div><div class="col-md-12"><div class="form-group"><div class="mt-radio-list radio_list_90345">' . $radio . '</div></div></div></div><div class="row li_row"><div class="col-md-12"><div class="field_extra_info_90345">' . $radio_inputs . '</div></div></div></div></div>';
                                break;
                            case 'checkbox':
                                foreach ($field['questionnaireFieldOptions'] as $options) {
                                    $checkbox .= '<label class="mt-checkbox mt-checkbox-outline"><input data-opt="54229" type="checkbox" name=' . $field['field_name'] . ' value="Value"> <p class="c_opt_name_54229">' . $options['field_option'] . '</p><span></span></label>';
                                }
                                foreach ($field['questionnaireFieldOptions'] as $options) {
                                    $checkbox_inputs .= '<div data-field="12633" class="row checkbox_row_12633" data-opt="54229"><div class="col-md-4"><div class="form-group"><input type="text" placeholder="Option"  class="c_opt form-control valid_input" value=' . $options['field_option'] . '></div></div><div class="col-md-4"><i class="margin-top-5 fa fa-plus-circle fa-2x default_blue add_more_checkbox" data-field="12633"></i></div><div class="col-md-4"><div class="form-group"><input type="hidden" value="Value" class="c_val form-control"></div></div></div>';
                                }
                                echo '<div class="li_12633 form_builder_field" style="width: 928.75px; height: auto;"><div class="all_div"><div class="row li_row"><div class="col-md-12"><button type="button" class="btn btn-primary btn-sm remove_bal_field " data-field="12633"><i class="fa fa-times"></i></button></div></div><hr><div class="row li_row form_output" data-type="checkbox" data-field="12633"><div class="col-md-12"><div class="form-group"><input type="text" name="label_12633" class="form-control form_input_label valid_input" placeholder="Multi Selectbox Field" data-field="12633" value=' . $field['field_label'] . '></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name="text_12633" class="form-control form_input_name" placeholder="Name" value="checkbox_12633"></div></div><div class="col-md-12"><div class="form-group"><div class="mt-checkbox-list checkbox_list_12633">' . $checkbox . '</div></div></div></div><div class="row li_row"><div class="col-md-12"><div class="field_extra_info_12633">' . $checkbox_inputs . '</div></div></div></div></div>';
                                break;
                            case 'number':
                                echo '<div class="li_62903 form_builder_field" style="width: 928.75px; height: 170px;"><div class="all_div"><div class="row li_row"><div class="col-md-6"><button type="button" class="btn btn-primary btn-sm remove_bal_field " data-field="62903"><i class="fa fa-times"></i></button></div><div class="col-md-6"><div class="form-check pull-right"><label class="form-check-label"><input data-field="62903" type="checkbox" class="form-check-input form_input_req" checked="">Required</label></div></div></div></div><hr><div class="row li_row form_output" data-type="number" data-field="62903"><div class="col-md-12"><div class="form-group"><input type="text" name="label_62903" class="form-control form_input_label valid_input valid" placeholder="Field Name" data-field="62903" aria-invalid="false" value="' . $field['field_label'] . '"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name="placeholder_62903" data-field="62903" class="form-control form_input_placeholder" placeholder="Placeholder"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name="' . $field['field_name'] . '" class="form-control form_input_name" placeholder="Name" value="number_62903"></div></div></div></div>';
                                break;
                            case 'date':
                                echo '<div class="li_9691 form_builder_field" style="width: 928.75px; height: 155px;"><div class="all_div"><div class="row li_row"><div class="col-md-6"><button type="button" class="btn btn-primary btn-sm remove_bal_field " data-field="9691"><i class="fa fa-times"></i></button></div><div class="col-md-6"><div class="form-check pull-right"><label class="form-check-label"><input data-field="9691" type="checkbox" class="form-check-input form_input_req" checked="">Required</label></div></div></div></div><hr><div class="row li_row form_output" data-type="date" data-field="9691"><div class="col-md-12"><div class="form-group"><input type="text" name="label_9691" class="form-control form_input_label valid_input valid" placeholder="Date Field" data-field="9691" aria-invalid="false" value="' . $field['field_label'] . '"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name="' . $field['field_name'] . '" class="form-control form_input_name" placeholder="Name" value="date-field_9691"></div></div></div></div>';
                                break;
                            case 'time':
                                echo '<div class="li_70745 form_builder_field" style="width: 928.75px; height: 155px;"><div class="all_div"><div class="row li_row"><div class="col-md-6"><button type="button" class="btn btn-primary btn-sm remove_bal_field " data-field="70745"><i class="fa fa-times"></i></button></div><div class="col-md-6"><div class="form-check pull-right"><label class="form-check-label"><input data-field="70745" type="checkbox" class="form-check-input form_input_req" checked="">Required</label></div></div></div></div><hr><div class="row li_row form_output" data-type="time" data-field="70745"><div class="col-md-12"><div class="form-group"><input type="text" name="label_70745" class="form-control form_input_label valid_input valid" placeholder="Time Input" data-field="70745" aria-invalid="false" value="' . $field['field_label'] . '"></div></div><div class="col-md-12"><div class="form-group"><input type="hidden" name="text_70745" class="form-control form_input_name" placeholder="Name" value="time-field_70745"></div></div></div></div>';
                                break;
                        }
                    }
                    endif;
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
$script = <<< JS

JS;

?>